spring:
  application:
    name: MongMong2 Account Book

  profiles: local

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/data/MM_ACCOUNT_BOOK;IFEXIST=TRUE;TRACE_LEVEL_FILE=4;FILE_LOCK=SOCKET;MODE=MySQL
    username: sa
    password:
    validation-query: SELECT 1

  jpa:
    database: h2
    hibernate.ddl-auto: true
    generate-ddl: true
    show-sql: true
    properties.hibernate.hbm2ddl.auto: create
    properties.hibernate.format_sql: true
    properties.hibernate.use_sql_comments: true

---

spring:
  profiles: dev

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/data/MM_ACCOUNT_BOOK;IFEXIST=TRUE;TRACE_LEVEL_FILE=4;FILE_LOCK=SOCKET;MODE=MySQL
    username: sa
    password:
    validation-query: SELECT 1

  jpa:
    database: h2
    hibernate.ddl-auto: true
    generate-ddl: true
    show-sql: true
    properties.hibernate.hbm2ddl.auto: create
    properties.hibernate.format_sql: true
    properties.hibernate.use_sql_comments: true

---

spring:
  profiles: real

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/data/MM_ACCOUNT_BOOK;IFEXIST=TRUE;TRACE_LEVEL_FILE=4;FILE_LOCK=SOCKET;MODE=MySQL
    username: sa
    password:
    validation-query: SELECT 1

  jpa:
    database: h2
    hibernate.ddl-auto: true
    generate-ddl: true
    show-sql: true
    properties.hibernate.hbm2ddl.auto: create
    properties.hibernate.format_sql: true
    properties.hibernate.use_sql_comments: true
